---
apiVersion: v1
data:
  prometheus_config.config: |-
    prometheus_config {
      enable: true,
      path: "/monitoring/metrics"
    }
kind: ConfigMap
metadata:
  name: promconfig
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/version: "0.0.1"
