apiVersion: v1
data:
  bucket.yaml: |-
    type: S3
    config:
      bucket: thanos
      endpoint: minio-s3:9000
      insecure: true
      signature_version2: true
      access_key: minio
      secret_key: minio123
kind: ConfigMap
metadata:
  name: s3-bucket
  labels:
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/version: "0.0.1"
